L_graph.o: Struct.c heading.h
	gcc -c -o L_graph.o Struct.c
sort.o: sort.c
	gcc -c -o sort.o sort.c
main.o: main.c heading.h
	gcc -c -o main.o main.c
T3: main.o L_graph.o
	gcc -o T3 main.o L_graph.o